useTabs: false
trailingComma: none
tabWidth: 2
semi: true
singleQuote: true
bracketSpacing: true
printWidth: 80
overrides:
    - files: "*.sol"
      options:
          printWidth: 120
          tabWidth: 4
    - files: "*.y(*)ml"
      options:
          singleQuote: false
          tabWidth: 4
